### PR TITLE
phase 1 - port mapping config as linked list + debug macro + many other improvements

### PR DESCRIPTION
**Pull request by ofekp**

### CODE REVIEW

**Comment by ofekp** [comment]
@Lan-Hekary please merge this into your PR, this will complete the first phase of this merge.
We can try to add the rest after I approve this. Test has started in my device, will take up to a week.

**Comment by ofekp** [comment]
@Lan-Hekary I have tested this PR for a week with no issues.
Please merge this into your PR and I will merge them into my repo so that we can have you as a contributor.
After that we can continue to review the other things in another PR.
What do you say?

**Comment by ofekp** [comment]
@Lan-Hekary reminder to review please.

**Comment by ofekp** [comment]
@Lan-Hekary Another reminder, I will want to merge it soon to the main repo, please let me know if you wish to have it merged from your PR.

**Comment by Lan-Hekary** [comment]
Sorry for the late response ..
I had so much work the past few weeks ..
I will merge the requests and we can discuss the rest of the changes another time ..

**Pull request merged**
